---
version: 1.0.0
slug: cybroscgiserver
name: CybroScgiServer
description: SCGI serer to communicate to PLCs from Cybrotech / Robotina
url: https://github.com/killer0071234/hassio-cybroscgiserver
codenotary: killer007@gmx.at
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  authorized_keys: []
  password: ""
ports:
  80/tcp: null
  4000/tcp: null
  8442/udp: null
