---
build_from:
  aarch64: ghcr.io/hassio-addons/base:16.3.2
  amd64: ghcr.io/hassio-addons/base:16.3.2
  armhf: ghcr.io/hassio-addons/base:16.3.2
  armv7: ghcr.io/hassio-addons/base:16.3.2
  i386: ghcr.io/hassio-addons/base:16.3.2
codenotary:
  base_image: killer007@gmx.at
  signer: killer007@gmx.at
