;-------------------------------------------------------------------------------
;                                 scgi_server
;-------------------------------------------------------------------------------

[ETH]
; ip address of network adapter used to communicate with controllers, leave empty to listen on all adapters
bind_address =

; port used for communication with controllers
; - when port is not specified, it is assigned from dynamic port range
; - when server is in local network and receive cybro sockets, use port 8442
; - when server is remote, use a fixed port and configure port forwarding on the router
port =

; enable to automatically detect controllers in the local network
autodetect_enabled = true

; broadcast address used for autodetect, leave empty to calculate automatically
autodetect_address =

; cybro sockets used to send events
; each socket consists of a socket id (1..255) and list of variables sorted by type
; variables of the same type are separated by comma, types are separated by semicolon
; socket = 1; socket_req, my_bit0, my_bit1; my_int0, my_int1; my_long0, my_long1
; socket = 10; socket_req; event_device, event_number, event_status;

; static ip address, use in local network when autodetect can't reach the controller
; [c20000]
; ip = 192.168.1.100
; port = 8442
; password =

[PUSH]
; server that receives and acknowledges push messages sent by controllers
; used to open the UDP channel that server can use to communicate with controllers
enabled = true

; time to delete controller from the list, after it stopped sending push messages [hours]
timeout_h = 24

[ABUS]
; time to resend the message when no reply is received [ms]
timeout_ms = 200

; number of retries before error is reported
number_of_retries = 3

; controller a-bus password, leave empty when controller is not protected
password =

[CACHE]
; time after which cache is invalidated and data is read from the controller [s], 0 to disable cache
valid_period_s = 0

; time after which data is still read from the cache, but a new read is sent to refresh the cache [s], 0 to disable refresh
request_period_s = 0

; time to periodically remove expired cache items [s], 0 to disable cleanup
cleanup_period_s = 0

[SCGI]
; ip address of network adapter used for scgi requests, leave empty to listen on all adapters
bind_address =

; address used by mqtt client and data logger to connect to scgi server, set to localhost for local machine
server_address = localhost

; port used as listener for scgi requests, used by all three apps
port = 4000

; limit access only to variables marked as 'user' in the plc program
only_user_variables = false

; include variable descriptions in xml response, disable when processing speed is critical
reply_with_descriptions = true

; rate at which mqtt client sends ping messages to the server, in order to keep the connection open [s]
keepalive = 30

; enable encryption for all scgi requests and answers, used by all three apps
tls_enabled = false

; token used for encripted communication, 64 alphanumeric characters
; token = PWFChKsSB4DJoe4WC09hBaOKRDq47hMYpFqfFyHda35TdRo3yOTGAWPmWjuOry47

[ALIAS]
; give each controller an alternate name, e.g. c20000.first_scan -> alpha.first_scan
; alphanumeric characters and underscore, no national characters, not case sensitive
; used by all three apps
; c20000 = alpha

;-------------------------------------------------------------------------------
;                                 mqtt_client
;-------------------------------------------------------------------------------

[MQTT]
; broker location and credentials, set localhost for the local machine
ip = localhost
port = 1883
username =
password =

; client identifier, must be unique for each client
client_id = cybrotech

; mqtt protocol version, use the one supported by the broker (3-v31, 4-v311, 5-v5)
version = 4

; rate at which the client sends ping messages to the broker, to keep the connection alive [s]
keepalive = 30

; quality of service, used for all transactions (0-send once, 1-send and confirm, 2-exactly once)
quality = 1

; last will and testament, message that will be sent to clients when publisher loses connection
lwt = myhome/will, disconnected

; enable encryption to make client to broker connection secure
tls_enabled = false

; publisher message format
; 0 - one topic per tag, legacy
; 1 - JSON object map, Home Assistant
; 2 - JSON records array, Iconics
; 3 - JSON SenML, industry standard
message_format = 1

[PUBLISH]
read_period = 5 ; read periodically and send if changed [s]
publish_period = 60 ; force sending in regular intervals [s]
topic = myhome/livingroom
var = c20000.lc00_qx00, c20000.bc00_qw00, c20000.th00_temperature, c20000.th00_setpoint

[PUBLISH]
read_period = 5 ; read periodically and send if changed [s]
publish_period = 60 ; force sending in regular intervals [s]
topic = myhome/livingroom
map = lights, c20000.lc00_qx00
map = blinds, c20000.bc00_qw00
map = temperature, c20000.th00_temperature
map = setpoint, c20000.th00_setpoint

[PUBLISH]
socket_id = 10
read_period = 0 ; never read
publish_period = 0 ; publish only on event
topic = myhome/events
var = c20000.event_device, c20000.event_number, c20000.event_status

[SUBSCRIBE]
topic = myhome/livingroom
var = c20000.lc00_qx00, c20000.bc00_qw00, c20000.th00_setpoint

[SUBSCRIBE]
topic = myhome/outdoor
map = temperature, c20000.outdoor_temperature

[SUBSCRIBE]
topic = myhome/commands
var = *

;-------------------------------------------------------------------------------
;                                 data_logger
;-------------------------------------------------------------------------------

[DBASE]
host = localhost
port = 3306
name = cybro
user = root
password = root
max_query_size = 100000

;-------------------------------------------------------------------------------
;                               common settings
;-------------------------------------------------------------------------------

[DEBUGLOG]
; available verbose levels: ERROR, WARNING, INFO, DEBUG
enabled = false
verbose_level = ERROR
log_to_file = true
max_file_size_kb = 1024
max_backup_count = 5

[LOCATIONS]
; location where temporary files are stored, relative to application directory
log_dir = log
alc_dir = alc
